### ISSUE TITLE
Installation instructions?

### ISSUE THREAD

**Issue by ndemou** [Slimmer-AI/bdsync#22]
Hi and thanks for this very useful tool!

It would be nice to include minimum installation instructions for those that aren't used to building software. 

Here's what works fine for Ubuntu 16.04 and 18.04 (I had the chance to test it):
```
# install utilities for building software (and wget and aunpack)
sudo apt install build-essential checkinstall wget
# install specific libraries that bdsync needs
sudo apt install libssl-dev pandoc 
# download and unzip bdsync
wget https://github.com/TargetHolding/bdsync/archive/master.zip
unzip bdsync.zip
# compile bdsync
cd bdsync-master/
make
# done -- you'll find bdsync in current path
```

And I **guess** that replacing the first two commands with these will work for CentOS/RedHat/Fedora:

```
sudo yum groupinstall 'Development Tools'
sudo yum install openssl-devel wget
```

**Comment by error10** [comment]
And `pandoc` is required to generate the man page.

**Comment by ndemou** [comment]
Yes it is... But I've includef pandoc in my instructions.

**Comment by rolffokkens-th** [comment]
Thanks! I included an initial COMPILING document
